<?php

function qldanhmuc_help($path, $args) {
  switch($path) {
    case 'admin/help#qldanhmuc':
      return t('Trợ giúp');
      break;
  }
}

function qldanhmuc_menu() {
    $items = array();
    $items['admin/qldanhmuc'] = array(
        'title' => 'Quản lý danh mục',
        'description' => 'Quản lý danh mục',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldanhmuc_form', 2, 3, 4),
        'access callback' => 'qldanhmuc_permission_check',
        'access arguments' => array(2),
        'file' => 'qldanhmuc.inc',
        //'access arguments' => array('Quản lý danh mục'),
        'type' => MENU_CALLBACK
    );
    
    $items['admin/qldanhmuc/edit'] = array(
        'title' => 'Cập nhật danh mục',
        'description' => 'Cập nhật danh mục',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldanhmuc_edit', 3, 4),
        'access callback' => 'qldanhmuc_permission_check',
        'access arguments' => array(2),
        'file' => 'qldanhmuc.inc',
        'type' => MENU_CALLBACK
    );
    
    $items['admin/qldanhmuc/settings'] = array(
        'title' => 'Thiết lập tham số quản lý danh mục',
        'description' => 'Thiết lập tham số module quản lý danh mục',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldanhmuc_settings', 1),
        'access callback' => 'qldanhmuc_permission_check',
        'access arguments' => array(2),
        'file' => 'qldanhmuc_settings.inc',
        //'access arguments' => array('Quản lý danh mục'),
        'type' => MENU_CALLBACK
    );
    $items['admin/qldanhmuc/import'] = array(
        'title' => 'Import files',
        'description' => 'Import files',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldanhmuc_import', 3),
        'access callback' => 'qldanhmuc_permission_check',
        'access arguments' => array(2),
        'file' => 'qldanhmuc_import.inc',
        //'access arguments' => array('Quản lý danh mục'),
        'type' => MENU_CALLBACK
    );

    return $items;
}

function qldanhmuc_permission() {
    return array(
        'Quản lý danh mục' => array('title' => t('Quản lý danh mục'),),
        'Xem danh mục' => array('title' => t('Xem danh mục'),),
    );
}

function qldanhmuc_permission_check($func, $subfunc = NULL) {
    switch ($func) {
        case 'import':
        case 'settings':
        case 'edit':
            return user_access('Quản lý danh mục');
        
        default:
            break;
    }
    return user_access('Quản lý danh mục') || user_access('Xem danh mục');
}