<?php

function qlctdt_help($path, $args) {
  switch($path) {
    case 'admin/help#qlctdt':
      return t('Module này dùng để quản lý CTĐT');
      break;
  }
}

function qlctdt_menu() {
    $items = array();
    $items['admin/qlctdt/settings'] = array(
        'title' => 'Thiết lập tham số module quản lý CTĐT',
        'description' => 'Thiết lập tham số module quản lý CTĐT',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlctdt_settings', 3, 4),
        'access callback' => TRUE,
        'file' => 'settings.inc',
        'access arguments' => array('administrater users'),
        'type' => MENU_CALLBACK
    );
    $items['admin/qlctdt'] = array(
        'title' => 'Quản lý CTĐT',
        'description' => 'Quản lý CTĐT',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlctdt_form', 2, 3),
        'access callback' => TRUE,
        'file' => 'qlctdt.inc',
        'access arguments' => array('administrater users'),
        'type' => MENU_CALLBACK
    );
    $items['admin/qlctdt/import'] = array(
        'title' => 'Import CTĐT',
        'description' => 'Import CTĐT từ file excel',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlctdt_import'),
        'access callback' => TRUE,
        'file' => 'qlctdt_import.inc',
        'access arguments' => array('administrater users'),
        'type' => MENU_CALLBACK
    );

    return $items;
}

function qlctdt_permission() {
    return array(
        'Quản lý CTĐT' => array(
        'title' => t('Quản lý CTĐT'),
        ),
        'Xem CTĐT' => array(
        'title' => t('Xem CTĐT'),
        ),
    );
}
