<?php

function qlgiangvien_init() {
	  // Include the js file
	  //drupal_add_js(drupal_get_path('module', 'qlgiangvien') . '/js/qlgiangvien.js');
}

function qlgiangvien_menu() {
    $items = array();
    $items['admin/qlgiangvien'] = array(
        'title' => t('Quản lý giảng viên'),
        'description' => 'Quản lý hồ sơ giảng viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form', 1),
        //'access callback' => 'user_is_logged_in',
        //'access callback' => TRUE,
        'file' => 'qlgiangvien.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    
    $items['admin/qlgiangvien/capnhat'] = array(
        'title' => 'Cập nhật thông tin giảng viên',
        'description' => 'Cập nhật thông tin giảng viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form_edit', 3),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_edit.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlgiangvien/settings'] = array(
        'title' => 'Tham số phân hệ quản lý giảng viên',
        'description' => 'Tham số phân hệ quản lý giảng viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form_settings', 1),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_settings.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlgiangvien/xem'] = array(
        'title' => 'Xem thông tin giảng viên',
        'description' => 'Xem thông tin giảng viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form_xem', 3),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_edit.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlgiangvien/them'] = array(
        'title' => 'Thêm giảng viên',
        'description' => 'Thêm giảng viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form_add', 1),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_edit.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlgiangvien/import'] = array(
        'title' => 'Import thông tin',
        'description' => 'Import thông tin',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_form_import', 3),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_import.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlgiangvien/syncportal'] = array(
        'title' => 'Đồng bộ dữ liệu với Portal',
        'description' => 'Đồng bộ dữ liệu với Portal',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlgiangvien_syncportal_form', 3, 4, 5),
        //'access callback' => TRUE,
        'file' => 'qlgiangvien_syncportal.inc',
        'access arguments' => array('UIT qlgiangvien'),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function qlgiangvien_help($path, $arg) {
  if ($path == 'admin/help/#qlgiangvien') {
    return t('This help for qlgiangvien');
  }
}

function qlgiangvien_user_login(&$edit, $account) {
  $_GET['destination'] = 'node';
}

function qlgiangvien_permission() {
  return array(
    'UIT qlgiangvien' => array('title' => t('UIT qlgiangvien')),
    'UIT qlgiangvien admin' => array('title' => t('UIT qlgiangvien admin')),
  );
}

/**
 * Trả về array form API.
 *
 * @param $field
 *   Array các thuộc tính lấy từ formfield trong DB
 * @param $fieldvalue
 *   Giá trị mặc định.
 * @param $options
 *   Các option của select box.
 * @param $readonly
 *   Chế dộ xem hay edit (true: xem).
 */
function render_form($field,$fieldvalue=NULL,$options=NULL,$readonly=TRUE) {
    $form = array(
        '#title' => $field->fieldname,
        '#default_value' => ($field->valuetype == 'date' && strlen($fieldvalue) == 10) ? date("d-m-Y",strtotime($fieldvalue)):$fieldvalue,
        '#type' => $field->fieldtype,
        '#required' => $field->required,
        '#disabled' => $readonly,);
        
    switch ($field->fieldtype) {
        case 'textfield':
            $form = array_merge($form, array('#size' => ($field->maxlength > 0 ? $field->maxlength:30)));
            break;
        case 'select':
            $form = array_merge($form, array('#options'=>$options));
            break;

        default:
            break;
    }
    
    return $form;
}