<?php

function qlhocvien_init() {
	  // Include the js file
	  drupal_add_js(drupal_get_path('module', 'qlhocvien') . '/js/qlhocvien.js');
}
function qlhocvien_menu() {
    $items = array();
    $items['admin/qlhocvien'] = array(
        'title' => t('Quản lý học viên'),
        'description' => 'Quản lý hồ sơ học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form', 1),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien.inc',
        'type' => MENU_NORMAL_ITEM
    );
    
    $items['admin/qlhocvien/capnhat'] = array(
        'title' => 'Cập nhật thông tin học viên',
        'description' => 'Cập nhật thông tin học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form_edit', 3),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_edit.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/settings'] = array(
        'title' => 'Tham số phân hệ quản lý học viên',
        'description' => 'Tham số phân hệ quản lý học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form_settings', 1),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_settings.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/xem'] = array(
        'title' => 'Xem thông tin học viên',
        'description' => 'Xem thông tin học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form_xem', 3),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_edit.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/them'] = array(
        'title' => 'Thêm học viên',
        'description' => 'Thêm học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form_add', 1),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_edit.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/import'] = array(
        'title' => 'Import thông tin',
        'description' => 'Import thông tin',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_form_import', 3),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2,3),
        'file' => 'qlhocvien_import.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/ghichu'] = array(
        'title' => 'Cập nhật thông tin ghi chú',
        'description' => 'Cập nhật thông tin ghi chú SV',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlhocvien_capnhat_ghichu', 3),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_edit.inc',
        'type' => MENU_NORMAL_ITEM
    );
    $items['admin/qlhocvien/qlcapnhat'] = array(
        'title' => 'Quản lý Cập nhật thông tin học viên',
        'description' => 'Quản lý Cập nhật thông tin học viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qlcapnhat_form', 1),
        'access callback' => 'qlhocvien_permission_check',
        'access arguments' => array(2),
        'file' => 'qlhocvien_qlcapnhat.inc',
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function qlhocvien_permission_check($func, $subfunc = NULL) {
    switch ($func) {
        case 'ghichu':
            return (user_access('UIT qlhocvien admin') || user_access('UIT qlhocvien cap nhat ghi chu'));        
        case 'xem':
        case 'capnhat':
            return user_access('UIT qlhocvien admin') || user_access('UIT qlhocvien CTSV');
        case 'import':
            if($subfunc == 'thongtin') return user_access('UIT qlhocvien admin');
            return user_access('UIT qlhocvien admin') || user_access('UIT qlhocvien CTSV');
        case 'qlcapnhat':
        case 'them':
        case 'settings':
            return user_access('UIT qlhocvien admin');

        default:
            break;
    }
    return user_access('UIT qlhocvien admin') || user_access('UIT qlhocvien CTSV') || user_access('UIT qlhocvien');
}

function qlhocvien_help($path, $arg) {
  if ($path == 'admin/help/#qlhocvien') {
    return t('This help for qlhocvien');
  }
}

function qlhocvien_user_login(&$edit, $account) {
  $_GET['destination'] = 'node';
}

function qlhocvien_permission() {
  return array(
    'UIT qlhocvien admin' => array('title' => t('UIT qlhocvien admin')),
    'UIT qlhocvien CTSV' => array('title' => t('UIT qlhocvien CTSV')),
    'UIT qlhocvien' => array('title' => t('UIT qlhocvien xem')),
    'UIT qlhocvien cap nhat ghi chu' => array('title' => t('UIT qlhocvien cập nhật ghi chú')),
  );
}

?>