<?php

function qldiem_help($path, $args) {
  switch($path) {
    case 'admin/help#qldiem':
      return t('Module này dùng để quản lý điểm hv');
      break;
  }
}

function qldiem_menu() {
    $items = array();

    $items['admin/qldiem'] = array(
        'title' => 'Quản lý điểm',
        'description' => 'Quản lý điểm',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem.inc',
        //'access arguments' => array('Xem diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/quanly'] = array(
        'title' => 'Quản lý điểm',
        'description' => 'Quản lý điểm',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_ql', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/import'] = array(
        'title' => 'Import điểm',
        'description' => 'Import điểm từ file excel',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_import', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_import.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

//    $items['admin/qldiem/importth'] = array(
//        'title' => 'Import điểm',
//        'description' => 'Import điểm từ file excel',
//        'page callback' => 'drupal_get_form',
//        'page arguments' => array('qldiem_form_importth', 1),
//        'access callback' => 'qldiem_permission_check',
//        'access arguments' => array(2),
//        'file' => 'qldiem_import.inc',
//        //'access arguments' => array('Quan ly diem'),
//        'type' => MENU_NORMAL_ITEM
//    );

    $items['admin/qldiem/xem'] = array(
        'title' => 'Xem bảng điểm một hv',
        'description' => 'Xem bảng điểm một hv',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_xemdiemhv', 3),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xemdiem.inc',
        //'access arguments' => array('Xem diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/in'] = array(
        'title' => 'In bảng điểm một hv',
        'description' => 'In bảng điểm một hv',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_inbangdiem', 3),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xemdiem.inc',
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/bangdiemtn'] = array(
        'title' => 'In bảng điểm tốt nghiệp một hv',
        'description' => 'In bảng điểm tốt nghiệp một hv',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_inbangdiemtn', 3),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xemdiem.inc',
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/xemdiem'] = array(
        'title' => 'Xem điểm một lớp',
        'description' => 'Xem điểm một lớp',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_xemdiem', 3, 4, 5, 6),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xemdiem.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/xoadiem'] = array(
        'title' => 'Xóa điểm một lớp',
        'description' => 'Xóa điểm một lớp',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_xoadiem', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xoadiem.inc',
        //'access arguments' => array('administrater users'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/edit'] = array(
        'title' => 'Sửa điểm của một sinh viên',
        'description' => 'Sửa điểm của một sinh viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_xemdiem_form_edit', 3),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_xemdiem.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/bangdiem'] = array(
        'title' => 'Xuất bảng điểm sinh viên',
        'description' => 'Xuất bảng điểm sinh viên',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_bangdiem', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_bangdiem.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/bangdiemth'] = array(
        'title' => 'Xuất bảng điểm tổng hợp',
        'description' => 'Xuất bảng điểm tổng hợp',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_form_bangdiemth', 1),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_bangdiemth.inc',
        //'access arguments' => array('Quan ly diem'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/qldiem/xuat/bangdiem/%/%'] = array(
        'title' => 'Xuất excel bảng điểm tổng hợp',
        'description' => 'Xuất excel bảng điểm tổng hợp',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('qldiem_export_bangdiem',4,5),
        'access callback' => 'qldiem_permission_check',
        'access arguments' => array(2),
        'file' => 'qldiem_export.inc',
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function qldiem_permission() {
    return array(
        'Quản lý điểm' => array(
        'title' => t('Quản lý điểm'),
        'description' => t('Quản lý điểm'),
        ),
        'Import điểm' => array(
        'title' => t('Import điểm'),
        'description' => t('Import điểm từ file excel'),
        ),
        'Xem điểm' => array(
        'title' => t('Xem điểm'),
        'description' => t('Xem điểm hv'),
        ),
    );
}

function qldiem_permission_check($func) {
    switch ($func) {
        case 'bangdiemth':
        case 'bangdiem':
        case 'quanly':
        case 'xoadiem':
        case 'edit':
            return user_access('Quản lý điểm');
        
        case 'import':
            return user_access('Import điểm');

        default:
            break;
    }
    return user_access('Quản lý điểm') || user_access('Import điểm') || user_access('Xem điểm');
}

function CapNhatTrangThai($mahv, $mamh=NULL) {
    //return TRUE;
    $q = db_select('uit_diem', 'd');
    $q->fields ('d');
    $q->condition('d.mahv', $mahv);
    $q->condition('d.trangthai', 0, '>');
    $q->condition('d.trangthai', 5, '<>');
    if($mamh) $q->condition('d.mamh', $mamh);
    $q->orderBy('d.hocky','ASC')->orderBy('d.mamh','ASC');
    $rows = $q->execute()->fetchAll();
    
    $arrDiem = array();    
    $rowid = 0;
    foreach ($rows as $row) {
        $arrDiem[$row->mamh][] = $rowid++;
    }
    
    foreach ($arrDiem as $mamh1 => $value) {
        $rowidfinal = $value[0];
        $caithien = FALSE;
        $tinhtrang = 0;
        //$sotc = $rows[$value[0]]->sotc;
        
        if(count($value) > 1) {
            $indmax = 0;
            for($i=0;$i<count($value)-1;$i++) {
                if($rows[$value[$indmax]]->diem >= 5) { //cải thiện
                    if($rows[$value[$i+1]]->diem <= $rows[$value[$indmax]]->diem) {
                        setTrangThai($rows[$value[$i+1]]->id, 3);
                    } else {
                        setTrangThai($rows[$value[$indmax]]->id, 3);
                        $indmax = $i+1;
                    }
                    $caithien = TRUE;
                    $tinhtrang = 3;
                } else { //trả nợ
                    setTrangThai($rows[$value[$i]]->id, 2);
                    $tinhtrang = 2;
                    $indmax = $i+1;
                }
            }
            $rowidfinal = $value[$indmax];
        }
        $ghichu = NULL;
        if($rowidfinal > $value[0] && $rows[$rowidfinal]->mamh != $rows[$value[0]]->mamh) {
            $strghichu = 'TN:'.$rows[$value[0]]->mamh;
            if($caithien) $strghichu = 'CT:'.$rows[$value[0]]->mamh;
            if($rows[$rowidfinal]->ghichu != '') {
                if(strpos($rows[$rowidfinal]->ghichu, $strghichu) === FALSE) {
                    $ghichu = $rows[$rowidfinal]->ghichu.'; '.$strghichu;
                }
            } else {
                $ghichu = $strghichu;
            }
        }
        setTrangThai($rows[$rowidfinal]->id, 1, $ghichu, $tinhtrang);
    }
    return TRUE;
}

function setTrangThai($did, $trangthai=1, $ghichu=NULL, $tinhtrang=NULL) {
    $arrUpdate = array('trangthai' => $trangthai);
    if($tinhtrang) $arrUpdate = array_merge ($arrUpdate, array('tinhtrang' => $tinhtrang));
    if($ghichu) $arrUpdate = array_merge ($arrUpdate, array('ghichu' => $ghichu));
    try {
        db_update('uit_diem')->fields($arrUpdate)->condition('id', $did)->condition('trangthai', 0, '<>')->execute();
    } catch (Exception $exc){
        drupal_set_message($exc->getMessage(),'error');
        return FALSE;
    }
    return TRUE;
}

function MonHocTuongDuong($mamoi, $ctdt = NULL) {
    $q = db_select('uit_monhoctd', 't')->fields('t', array('mamh1', 'mamh2'))->condition('mamh2', $mamoi);
    if($ctdt) $q->condition('ctdt', "%$ctdt%", 'LIKE');
    return $q->execute()->fetchAllKeyed();
}

function Xeploai($diem) {
    if($diem >= 9) {
        return 'Xuất Sắc';
    } elseif($diem >= 8) {
        return 'Giỏi';
    } elseif($diem >= 7) {
        return 'Khá';
    } elseif($diem >= 6) {
        return 'TB Khá';
    } elseif($diem >= 5) {
        return 'Trung Bình';
    }
    return 'Không đạt';
}

function XetDieuKienThiTN($mahv, $sohocky = 10) {
    $arrMonHocBB = array('TH107','TH103','TH108','TH102','TH112','TH502');
    //Kiểm tra 6 môn bắt buộc
    $q = db_select('uit_diem','t');
    $q->addExpression('count(id)','tong');
    $q->condition('mahv',$mahv)->condition('mamh',$arrMonHocBB,'IN');
    $q->condition('diem',5,'>=')->condition('trangthai',1);
    $somon = $q->execute()->fetchField();
    if(!$somon || $somon < 6) return FALSE;
    if($sohocky) {
        //Kiểm tra nợ tối đa 2 môn từ HP1->HP9
        $q = db_select('uit_diem','t');
        $q->addExpression('count(id)','tong');
        $q->condition('mahv',$mahv);
        $q->condition('hocky',$sohocky,'<');
        $q->condition('diem',5,'<')->condition('trangthai',1);
        $somon = $q->execute()->fetchField();
        if($somon && $somon > 2) return FALSE;
    }
    return TRUE;
}

function XetDieuKienTN($mahv) {
    $q = db_select('uit_diem','t');
    $q->addExpression('count(id)','tong');
    $q->condition('mahv',$mahv);
    $q->condition('diem',5,'<')->condition('trangthai',1);
    $somon = $q->execute()->fetchField();
    if($somon && $somon > 0) return FALSE;
    return TRUE;
}

/**
 * Tách họ, tên từ $hoten
 * @param string $hoten
 * @return array('ho','ten')
 */
function TachHoTen($hoten) {
    $hoten = trim($hoten);
    if($hoten == '') return;
    $arr = explode(' ', $hoten);
    if(count($arr) == 1) {
        return array('ho'=>NULL, 'ten'=>$hoten);
    } else {
        $ten = $arr[count($arr)-1];
        unset($arr[count($arr)-1]);
        $ho = implode(' ', $arr);
        return array('ho'=>$ho, 'ten'=>$ten);
    }
    return;
}